spring:
  application:
    name: binance-kafka-producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

# Binance WebSocket Configuration
binance:
  websocket:
    base-url: wss://stream.binance.com:9443
    symbols: btcusdt,ethusdt,bnbusdt
    streams:
      - trade

# Kafka Topics
kafka:
  topics:
    raw-trades: crypto-raw-trades

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.crypto: DEBUG
    org.apache.kafka: INFO